name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet pack src/QLeatherMan.sln --configuration Release
    - name: publish to nuget
      run: dotnet nuget push src/bin/nupkg/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --skip-duplicate --source https://api.nuget.org/v3/index.json
